### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8 

### ISSUE THREAD

**Issue by mattiassvedhem** [kristianmandrup/sugar-high#16]
```
[GEM_ROOT]/gems/sugar-high-0.6.3/lib/sugar-high/blank.rb:30:in `=~'
[GEM_ROOT]/gems/sugar-high-0.6.3/lib/sugar-high/blank.rb:30:in `!~'
[GEM_ROOT]/gems/sugar-high-0.6.3/lib/sugar-high/blank.rb:30:in `blank?'
[GEM_ROOT]/gems/activemodel-3.2.2/lib/active_model/validator.rb:152:in `block in validate'
[GEM_ROOT]/gems/activemodel-3.2.2/lib/active_model/validator.rb:150:in `each'
[GEM_ROOT]/gems/activemodel-3.2.2/lib/active_model/validator.rb:150:in `validate'
[GEM_ROOT]/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:310:in `_callback_before_226'
[GEM_ROOT]/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:418:in `_run__1456008976144114989__validate__501779645816374209__callbacks'
[GEM_ROOT]/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:405:in `__run_callback'
[GEM_ROOT]/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:385:in `_run_validate_callbacks'
[GEM_ROOT]/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
[GEM_ROOT]/gems/mongoid-2.4.11/lib/mongoid/callbacks.rb:43:in `run_callbacks'
[GEM_ROOT]/gems/activemodel-3.2.2/lib/active_model/validations.rb:212:in `run_validations!'
[GEM_ROOT]/gems/activemodel-3.2.2/lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
[GEM_ROOT]/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:404:in `block in _run__1456008976144114989__validation__501779645816374209__callbacks'
[GEM_ROOT]/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_954'
```

Any idea what this error comes from?
Thanks

**Comment by kristianmandrup** [comment]
Try version 0.7

**Comment by mattiassvedhem** [comment]
Ah thanks, will do, just it as a dependency of cantango which was set at 0.6.0.

**Comment by kristianmandrup** [comment]
oh. Well, if you have a version of cantango that is working for you please let me know. Then please post that version in your repo with an updated sugar-high dependency that works. 
Then I will post it in the cantango group and on the cantango main page, that this is the currently "stable" version now, until I have time or someone else decides to work on this project to update it.
Thanks ;)
